"""Generate pinyin_phrases.h — a phrase table for the Cardputer IME.

When the user types a multi-syllable pinyin like "nihao", the IME splits it
into syllables and looks up matching phrases. This file contains the most
common 2-4 character phrases with their pinyin, ordered by frequency.

The phrase list is derived from jieba's dictionary: we take words of length
2-4 that appear frequently, compute their full pinyin (without tones), and
store them sorted by frequency.
"""
import os
import sys
from collections import defaultdict

import jieba
import pypinyin

# Force jieba to load its dictionary before reading FREQ.
jieba.initialize()

# Collect candidate phrases from jieba's dictionary.
# We want common 2-4 char phrases with their concatenated pinyin.
phrases = []
for word, freq in jieba.dt.FREQ.items():
    if freq < 500:  # keep the table small; 500 covers all common phrases
        continue
    if len(word) < 2 or len(word) > 4:
        continue
    # All characters must be CJK in GB2312 (the font only covers those).
    if not all('\u4e00' <= ch <= '\u9fa5' for ch in word):
        continue
    try:
        for ch in word:
            ch.encode('gb2312')
    except UnicodeEncodeError:
        continue
    # Compute pinyin.
    pys = pypinyin.pinyin(word, style=pypinyin.NORMAL, errors=['default'])
    if not pys or len(pys) != len(word):
        continue
    if any(not p or not p[0] for p in pys):
        continue
    py = ''.join(p[0] for p in pys)
    # Sanity: pinyin should be all lowercase letters.
    if not py.isalpha() or not py.islower():
        continue
    phrases.append((freq, py, word))

# Sort by frequency descending.
phrases.sort(key=lambda x: -x[0])

# Deduplicate: keep only the highest-frequency phrase for each (pinyin) key,
# but allow multiple phrases with different characters for the same pinyin.
# Actually, keep top 5 phrases per pinyin to give the user choices.
by_pinyin = defaultdict(list)
for freq, py, word in phrases:
    by_pinyin[py].append((freq, word))

# Build the final table: sorted by pinyin for binary search.
table = []
for py in sorted(by_pinyin):
    words = by_pinyin[py]
    # Keep top 5 by frequency.
    words.sort(key=lambda x: -x[0])
    top = words[:3]  # max 3 phrase candidates per pinyin
    chars = ''.join(w for _, w in top)
    table.append((py, chars))

out_dir = os.path.dirname(os.path.abspath(__file__))
hdr = os.path.join(out_dir, "firmware", "ask_master_ble", "pinyin_phrases.h")

with open(hdr, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by gen_pinyin_dict.py — do not edit.\n")
    f.write("// Multi-syllable phrase table for the pinyin IME.\n")
    f.write("// Key: concatenated pinyin (e.g. \"nihao\"). Value: candidate phrases.\n")
    f.write("#pragma once\n#include <stddef.h>\n#include <stdint.h>\n\n")
    f.write(f"static constexpr size_t PHRASE_ENTRY_COUNT = {len(table)};\n\n")
    f.write("struct PhraseEntry {\n")
    f.write("    const char* pinyin;\n")
    f.write("    const char* phrases;  // UTF-8, NUL-terminated, most frequent first\n")
    f.write("};\n\n")
    f.write("static const PhraseEntry phraseTable[] PROGMEM = {\n")
    for py, chars in table:
        f.write('    {"%s","%s"},\n' % (py, chars))
    f.write("};\n")

# Stats
total_bytes = sum(len(py) + 1 + len(chars) * 3 for py, chars in table)
print(f"wrote {hdr}")
print(f"  entries: {len(table)}")
print(f"  approx size (UTF-8): {total_bytes} bytes ({total_bytes/1024:.0f} KB)")
for check in ("nihao", "shijian", "zhongguo", "xiexie", "buguo"):
    for py, chars in table:
        if py == check:
            print(f"  {py}: {chars[:12]}")
            break
    else:
        print(f"  {check}: (not found)")
