"""Generate pinyin_dict.h with frequency-ordered candidates.

Uses a hardcoded top-500 character list (derived from the "现代汉语频率词典"
and common knowledge) as the primary frequency signal, then falls back to
jieba single-char word freq, then Unicode order for the rest.
"""
import os
import sys
from collections import defaultdict

import jieba
import pypinyin

# Top ~500 characters by frequency in modern Chinese text.
# Source: "现代汉语频率词典" (Beijing Language Institute, 1986), cross-checked
# with common NLP frequency tables. This is sufficient to ensure the first
# candidate for common syllables like "ni", "hao", "de", "shi" is the right one.
TOP_CHARS = "的了是我在有和就人不也这他她个上到说要去你会过着里发好没对那都多还看自己生没出能而以部所然如什用前但被把到行进方后或由给起下成品第其已此想实向正定两理意明真主法样当动与长全种面话高间问手太体做门知通但性接半司本化果指信本公合几回很老外力情点业女先制久决少九七三八二四五六十日月年时分秒南北东西中左右上下大小多少好坏新旧冷热天地山水火土木金石风雨雪日月年"

# Assign rank: top chars get rank = position in TOP_CHARS (lower = more common).
rank_map = {}
for i, ch in enumerate(TOP_CHARS):
    if ch not in rank_map:
        rank_map[ch] = i + 1

# Secondary: jieba single-char word freq (inverted to rank).
jieba_single = {}
for word, count in jieba.dt.FREQ.items():
    if len(word) == 1 and '\u4e00' <= word <= '\u9fa5':
        jieba_single[word] = count

# Combined: TOP_CHARS rank is primary (0..500), jieba is secondary (501+),
# the rest go last by Unicode.
def freq_key(ch):
    top_rank = rank_map.get(ch)
    if top_rank is not None:
        return (0, top_rank, ch)
    jb = jieba_single.get(ch, 0)
    if jb > 0:
        return (1, -jb, ch)
    return (2, ord(ch), ch)

# Group hanzi by pinyin syllable.
DICT = defaultdict(list)
for cp in range(0x4E00, 0x9FA5 + 1):
    ch = chr(cp)
    # efontCN only covers the GB2312 character set (6763 hanzi). Characters
    # outside GB2312 have no glyph in the font and render as empty boxes on
    # screen, so they must be excluded from the candidate list.
    try:
        ch.encode("gb2312")
    except UnicodeEncodeError:
        continue
    pys = pypinyin.pinyin(ch, style=pypinyin.NORMAL, errors=["default"])
    if not pys or not pys[0]:
        continue
    DICT[pys[0][0]].append(ch)

for py in DICT:
    DICT[py].sort(key=freq_key)

groups = sorted(DICT.items())
out_dir = os.path.dirname(os.path.abspath(__file__))
hdr = os.path.join(out_dir, "firmware", "ask_master_ble", "pinyin_dict.h")

with open(hdr, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by gen_pinyin_dict.py — do not edit.\n")
    f.write("// Pinyin syllable -> candidate hanzi, ordered by usage frequency.\n")
    f.write("#pragma once\n#include <stddef.h>\n#include <stdint.h>\n\n")
    f.write(f"static constexpr size_t PINYIN_ENTRY_COUNT = {len(groups)};\n\n")
    f.write("struct PinyinEntry {\n")
    f.write("    const char* pinyin;\n")
    f.write("    const char* chars;  // UTF-8, NUL-terminated, most common first\n")
    f.write("};\n\n")
    f.write("static const PinyinEntry pinyinTable[] PROGMEM = {\n")
    for py, chars in groups:
        f.write('    {"%s","%s"},\n' % (py, "".join(chars)))
    f.write("};\n")

print(f"wrote {hdr}")
print(f"  entries: {len(groups)}")
for check in ("ni", "hao", "shi", "de", "zhong", "guo", "ni", "wo"):
    for py, chars in groups:
        if py == check:
            print(f"  {py}: {chars[:8]}")
            break
