#ifndef CONFIG_H
#define CONFIG_H

#define BEEP_FREQ_ASK     1000
#define BEEP_FREQ_CONFIRM 1300
#define BEEP_FREQ_CHOOSE  900
#define BEEP_FREQ_ESCALATE 1500
#define BEEP_DURATION_MS  150
#define BEEP_ANSWER_FREQ  1400
#define BEEP_ANSWER_DURATION_MS 80

#endif
